version: "3"
services:
  data:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    expose:
      - "8501"
  db:
    build: ./chainlit_app
    ports:
      - "8080:8080"
    expose:
      - "8080"
